Extract forms into their own components and fix support us cards
RealEskalate/a2sv.org pull request #17
Opened 2020-10-30 14:06 UTC by ZBeimnet

2020-10-30 15:00 UTC, TripleThreads requested changes

2020-10-30 15:00 UTC, TripleThreads commented on Frontend/pages/support.vue
> +      'Q & A': false,
why didn't you use a single variable that stores in string? for example form_type: "interview"

2020-11-06 12:46 UTC, ZBeimnet commented on Frontend/pages/support.vue
> +import QandAForm from '@/components/Support/QandAForm'
Yeah, this is a better way. Thanks!

2020-11-07 16:58 UTC, TripleThreads commented on Frontend/pages/support.vue
> +    <v-container style="margin-top: -75px">
I wonder what this looks on mobile :)

2020-11-07 17:00 UTC, TripleThreads commented on Frontend/pages/support.vue
> +      </div>
I would like this in methods.

2020-11-07 17:09 UTC, TripleThreads approved these changes

2020-11-07 19:52 UTC, TripleThreads commented
All issues are addressed.

2020-11-07 19:53 UTC, merged