Anteneh.information and event features
RealEskalate/a2sv.org pull request #33
Opened 2020-11-17 18:57 UTC by AntenehAdmasu

Error handling centralized

2020-11-17 19:05 UTC, MohammedAlewi requested changes

2020-11-17 19:05 UTC, MohammedAlewi commented on Backend/controllers/EventController.js
> +        res.status(404).send(`Event with id ${id} is not found`)
return statement :)

2020-11-17 19:06 UTC, MohammedAlewi reviewed
looks good only some missed return statments :)

2020-11-17 19:57 UTC, MohammedAlewi approved these changes

2020-11-17 20:14 UTC, Khalid-Sultan approved these changes

2020-11-18 05:42 UTC, Infinidrix reviewed
Left some comments but not sure if everything works like it's supposed to, would be great to have tests in the same PR as the changes.

2020-11-18 05:42 UTC, Infinidrix commented on Backend/index.js
> +app.use((err, req, res, next) => {
From ExpressJS [website](https://expressjs.com/en/guide/error-handling.html#writing-error-handlers): _You define error-handling middleware last, after other app.use() and routes calls_

2020-11-18 05:42 UTC, Infinidrix commented on Backend/middlewares/validator.js
> +      return res.status(422).send(response)
Both this function and the centralized error handler sends the response so there will be a conflict there I think. Maybe a res.headersSent check on the universal handler would resolve the issue.

2020-11-18 05:42 UTC, Infinidrix commented on Backend/routes/EventRouter.js
> +router.put('/:id/links', eventController.addEventLink)
Wouldn't inputValidator be necessary for the two put methods routes

2020-11-18 08:14 UTC, AntenehAdmasu commented on Backend/index.js
> +app.use((err, req, res, next) => {
At line 30, we are using `app.use(router)` to import all routes prepared on startup/routes. The error handling middleware is invoked from `process.on(unhandledRejection)` so I don't think the position matters.

2020-11-18 08:23 UTC, AntenehAdmasu commented on Backend/routes/EventRouter.js
> +router.put('/:id/links', eventController.addEventLink)
Nice catch :) I'll update accordingly

2020-11-18 08:23 UTC, AntenehAdmasu commented on Backend/middlewares/validator.js
> +      return res.status(422).send(response)
This error handler is meant to catch input errors from req.body and will be applied only when requested in the middleware, mostly for POST and PUT methods. The universal handler handles all other errors during the execution of any function.

2020-11-18 10:29 UTC, Infinidrix commented on Backend/index.js
> +app.use((err, req, res, next) => {
What confused me was the `app.use(router)` on line 22. And also according to [this](https://expressjs.com/en/guide/writing-middleware.html#:~:text=Every%20time%20the%20app%20receives,first%20are%20also%20executed%20first.) I think the orderings matter like if there was an error in bodyParser then it'll catch the error, but if it is in routes it won't.

2020-11-18 11:19 UTC, AntenehAdmasu commented on Backend/index.js
> +app.use((err, req, res, next) => {
I just saw it now. We had to `app.use(router)` lines at 22 and 30 by mistake. I'll remove the later. Thanks for pointing that out :). I'm about to write the unit tests and things will settle by then I hope 👍

2020-11-18 11:23 UTC, closed without merging